### ISSUE TITLE
Gearbox doesn't down shitf

### ISSUE THREAD

**Issue by raywo22** [GinoLin980/Forza-Horizon-realistic-gearbox#1]
Thx for this mod, but, the gearbox shift up very well but never down shift

**Comment by GinoLin980** [comment]
on which driving condition? casual drive or heavy flooring

**Comment by raywo22** [comment]
> dans quelles conditions de conduite ? conduite occasionnelle ou revêtement de sol lourd

in all conditions

**Comment by GinoLin980** [comment]
> > dans quelles conditions de conduite ? conduite occasionnelle ou revêtement de sol lourd
> 
> in all conditions, 

i uploaded the new code and exe, you can try it by download it from the "code" section. 
🥳

**Comment by GinoLin980** [comment]
**I UPLOAD A NEW VERSION (V2) , DON'T FORGET TO GIVE IT A TRY**
**THE NEW VERSION WILL BRING YOU DIFFERENT EXPERIENCE**

**Comment by raywo22** [comment]
Thank you very much for your work, I don't have access to my computer at
the moment. But I'm going to try this as soon as possible.

**Comment by raywo22** [comment]
> **JE TÉLÉCHARGE UNE [NOUVELLE VERSION (V2)](https://github.com/GinoLin980/Forza-Horizon-realistic-gearbox/releases) , N'OUBLIEZ PAS DE L'ESSAYER, ** **LA NOUVELLE VERSION VOUS APPORTERA UNE EXPÉRIENCE DIFFÉRENTE**

I'm sorry but it still doesn't work no matter how I drive. Maybe the problem is with me and not with your mod.

**Comment by GinoLin980** [comment]
> > **JE TÉLÉCHARGE UNE [NOUVELLE VERSION (V2)](https://github.com/GinoLin980/Forza-Horizon-realistic-gearbox/releases) , N'OUBLIEZ PAS DE L'ESSAYER, ** **LA NOUVELLE VERSION VOUS APPORTERA UNE EXPÉRIENCE DIFFÉRENTE**
> 
> I'm sorry but it still doesn't work no matter how I drive. Maybe the problem is with me and not with your mod. 

thank for your supporting, I'll try to find the problem in the future ☺️
