### ISSUE TITLE
Does NOT work in Forza Horizon 4

### ISSUE THREAD

**Issue by ThisCrazyGamer09** [GinoLin980/Forza-Horizon-realistic-gearbox#2]
I understood it would work in Forza Horizon 4 but every time I try to run it does not start, it just says "WORKED" .

**Comment by GinoLin980** [comment]
did you try the new version and check the settings

**Comment by ThisCrazyGamer09** [comment]
Still not working, I think its a set up issue, i have the UDP and the IP correctly, if you could send me a picture of your settings so I can see whats wrong.
Thanks

**Comment by GinoLin980** [comment]
![image](https://github.com/GinoLin980/Forza-Horizon-realistic-gearbox/assets/87902619/e76ebfd8-c7fe-4815-8209-e7d4e12996be)
![image](https://github.com/GinoLin980/Forza-Horizon-realistic-gearbox/assets/87902619/d3a5a3f0-fa76-4bb9-897f-5271462ff337)
make sure that when you press q and e in the game does it shift down and up. And don't forget to try the new version

**Comment by ThisCrazyGamer09** [comment]
I installed the new version and the q and e are for down and upshift but still isn't working, since i installed the new version it tellms me to select the UDP port to 8000 (it's already set to 8000) and IP to 127.0.0.1 (Again it's already set to 127.0.0.1)

**Comment by GinoLin980** [comment]
I understand. You could try disabling your firewall, as it appears to be related to your network configuration. 
Considering I just reinstalled my PC a few days ago and haven't set up any network configurations, it's reasonable to assume that this program would work on most Windows computers.

**Comment by ThisCrazyGamer09** [comment]
I think it is not the firewall, The Firewall warns me when it is blocking something (It has not warned me), also I have tried it in Forza Horizon 5 and it works.

**Comment by GinoLin980** [comment]
I’m not sure about the specific solution to this problem yet, but I will continue to look for possible solutions. If there is any further information or error messages, that would help to better understand the issue.

**Comment by GinoLin980** [comment]
@ThisCrazyGamer09 
Happy to inform good news for the problem you met. 
With the research I made, I figured out how to fix and made extra programs to solve it. You can check it out on the [README.md](https://github.com/GinoLin980/Forza-Horizon-realistic-gearbox) of this repository.

Best Regard,
Gino Lin
